from dataclasses import dataclass


@dataclass
class Strategy:
    """
    Represents a possible decision generated by Aegis.
    """

    name: str
    description: str
    estimated_cost: float
    expected_benefit: float